"""Add scanned_game

Revision ID: 00f983d4cb7d
Revises: 456e955fcdd4
Create Date: 2026-09-05 15:15:06.884809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f983d4cb7d'
down_revision: Union[str, Sequence[str], None] = '456e955fcdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanned_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=64), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_scanned_game_user_game')
    )
    op.create_index(op.f('ix_scanned_game_user_id'), 'scanned_game', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanned_game_user_id'), table_name='scanned_game')
    op.drop_table('scanned_game')
    # ### end Alembic commands ###
