"""Add bandit_pull and bandit_arm_state

Revision ID: 3cfa7c1e498d
Revises: 87e8c83fe16c
Create Date: 2026-09-05 14:23:41.743962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfa7c1e498d'
down_revision: Union[str, Sequence[str], None] = '87e8c83fe16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandit_arm_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arm', sa.String(length=32), nullable=False),
    sa.Column('precision_matrix', sa.Text(), nullable=False),
    sa.Column('weighted_reward_sum', sa.Text(), nullable=False),
    sa.Column('pull_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arm')
    )
    op.create_table('bandit_pull',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('arm', sa.String(length=32), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rewarded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandit_pull_puzzle_id'), 'bandit_pull', ['puzzle_id'], unique=False)
    op.create_index(op.f('ix_bandit_pull_user_id'), 'bandit_pull', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bandit_pull_user_id'), table_name='bandit_pull')
    op.drop_index(op.f('ix_bandit_pull_puzzle_id'), table_name='bandit_pull')
    op.drop_table('bandit_pull')
    op.drop_table('bandit_arm_state')
    # ### end Alembic commands ###
