"""Add quality_score to personal_puzzle_candidate

Revision ID: 456e955fcdd4
Revises: 3cfa7c1e498d
Create Date: 2026-09-05 14:27:20.170589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456e955fcdd4'
down_revision: Union[str, Sequence[str], None] = '3cfa7c1e498d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_puzzle_candidate', sa.Column('quality_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_puzzle_candidate', 'quality_score')
    # ### end Alembic commands ###
