"""Add game_import_progress and personal_puzzle_candidate

Revision ID: 58551290ebec
Revises: 47edfd1afdd0
Create Date: 2026-09-04 22:20:45.961594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58551290ebec'
down_revision: Union[str, Sequence[str], None] = '47edfd1afdd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_import_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chess_com_username', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('games_processed', sa.Integer(), nullable=False),
    sa.Column('puzzles_found', sa.Integer(), nullable=False),
    sa.Column('last_archive', sa.String(length=16), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_import_progress_user_id'), 'game_import_progress', ['user_id'], unique=True)
    op.create_table('personal_puzzle_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(length=100), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_personal_puzzle_candidate_user_id'), 'personal_puzzle_candidate', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_puzzle_candidate_user_id'), table_name='personal_puzzle_candidate')
    op.drop_table('personal_puzzle_candidate')
    op.drop_index(op.f('ix_game_import_progress_user_id'), table_name='game_import_progress')
    op.drop_table('game_import_progress')
    # ### end Alembic commands ###
