"""add themes to personal_puzzle_candidate

Revision ID: 5b0cce0ecf81
Revises: 67046a9a61cd
Create Date: 2026-09-11 13:58:44.888427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0cce0ecf81'
down_revision: Union[str, Sequence[str], None] = '67046a9a61cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_puzzle_candidate', sa.Column('themes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_puzzle_candidate', 'themes')
    # ### end Alembic commands ###
