"""Add tactical_sharpness columns to puzzle_quality_training_example

Revision ID: 67046a9a61cd
Revises: 2b74b832c503
Create Date: 2026-09-11 09:44:46.844795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67046a9a61cd'
down_revision: Union[str, Sequence[str], None] = '2b74b832c503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='0' (rather than the autogenerated bare NOT NULL) so
    # this applies cleanly against an existing non-empty table — real
    # values get backfilled immediately after by a one-off script (see
    # CLAUDE.md's Phase 2.5 tactical_sharpness note); the default just
    # satisfies the NOT NULL constraint for the ALTER itself.
    op.add_column('puzzle_quality_training_example', sa.Column('num_checking_moves', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('puzzle_quality_training_example', sa.Column('num_hanging_pieces', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('puzzle_quality_training_example', sa.Column('material_imbalance', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('puzzle_quality_training_example', sa.Column('num_pinned_pieces', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle_quality_training_example', 'num_pinned_pieces')
    op.drop_column('puzzle_quality_training_example', 'material_imbalance')
    op.drop_column('puzzle_quality_training_example', 'num_hanging_pieces')
    op.drop_column('puzzle_quality_training_example', 'num_checking_moves')
    # ### end Alembic commands ###
