"""Add setup_swing_cp and puzzle_quality_training_example

Revision ID: 87e8c83fe16c
Revises: eb50c23a1e58
Create Date: 2026-09-05 01:26:51.462731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e8c83fe16c'
down_revision: Union[str, Sequence[str], None] = 'eb50c23a1e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle_quality_training_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('fen', sa.String(length=100), nullable=False),
    sa.Column('setup_move', sa.String(length=8), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('setup_swing_cp', sa.Integer(), nullable=False),
    sa.Column('forced', sa.Boolean(), nullable=False),
    sa.Column('refutation_gap_cp', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('nb_plays', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_quality_example_source_external_id')
    )
    op.add_column('personal_puzzle_candidate', sa.Column('setup_swing_cp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_puzzle_candidate', 'setup_swing_cp')
    op.drop_table('puzzle_quality_training_example')
    # ### end Alembic commands ###
