"""add personal_puzzle_candidate game_url

Revision ID: c0701c521d02
Revises: 00f983d4cb7d
Create Date: 2026-09-05 20:12:13.197655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0701c521d02'
down_revision: Union[str, Sequence[str], None] = '00f983d4cb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_puzzle_candidate', sa.Column('game_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_puzzle_candidate', 'game_url')
    # ### end Alembic commands ###
