"""add rating_low and rating_high to personal_puzzle_candidate

Revision ID: c2bece89cd42
Revises: 5b0cce0ecf81
Create Date: 2026-09-25 15:04:42.191367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bece89cd42'
down_revision: Union[str, Sequence[str], None] = '5b0cce0ecf81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_puzzle_candidate', sa.Column('rating_low', sa.Integer(), nullable=True))
    op.add_column('personal_puzzle_candidate', sa.Column('rating_high', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_puzzle_candidate', 'rating_high')
    op.drop_column('personal_puzzle_candidate', 'rating_low')
    # ### end Alembic commands ###
