"""Add forced and refutation_gap_cp to personal_puzzle_candidate

Revision ID: eb50c23a1e58
Revises: 58551290ebec
Create Date: 2026-09-05 01:14:02.561668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb50c23a1e58'
down_revision: Union[str, Sequence[str], None] = '58551290ebec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_puzzle_candidate', sa.Column('forced', sa.Boolean(), nullable=True))
    op.add_column('personal_puzzle_candidate', sa.Column('refutation_gap_cp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_puzzle_candidate', 'refutation_gap_cp')
    op.drop_column('personal_puzzle_candidate', 'forced')
    # ### end Alembic commands ###
